BlogBundle\Entity\author:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\authorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        info:
            type: string
            length: '255'
            unique: true
    lifecycleCallbacks: {  }
